models:
  - type: main
    engine: ollama
    model: phi3:mini
    parameters:
      base_url: http://host.docker.internal:11434
  
  - type: embeddings
    engine: FastEmbed
    model: all-MiniLM-L6-v2