@startuml
participant "Application\nCode" as A

skinparam Participant {
  RoundCorner 10

  BackgroundColor<<LLMRails >> 76b900
  FontColor<<LLMRails>> white
  BorderColor<<LLMRails>> green
}

participant LLMRails <<LLMRails>>

activate A
A->LLMRails: "Hello there!"
activate LLMRails

LLMRails->LLM: TaskPrompt [generate_user_intent]
activate LLM
return "express greeting"

LLMRails->LLMRails: bot express greeting\nbot ask how are you

LLMRails->LLMRails: "Hello World!\nHow are you doing?"

return #green "Hello World!\nHow are you doing?"

participant LLM
hide footbox
hide stereotype
scale 2
@enduml
