@startuml
participant "Application\nCode" as A

skinparam Participant {
  RoundCorner 10

  BackgroundColor<<LLMRails >> 76b900
  FontColor<<LLMRails>> white
  BorderColor<<LLMRails>> green
}

participant LLMRails <<LLMRails>>

activate A
A->LLMRails: "What is the capital of France?"
activate LLMRails

LLMRails->LLM: TaskPrompt [generate_user_intent]
activate LLM
return "ask general question"

LLMRails->LLM: TaskPrompt [generate_next_steps]
activate LLM
return "bot response for general question"

LLMRails->LLM: TaskPrompt [generate_bot_message]
activate LLM
return "The capital of France is Paris..."

return #76b900 "The capital of France is Paris..."

participant LLM
hide footbox
hide stereotype
scale 2
@enduml
