instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the NVIDIA AI Enterprise Bot.
      The bot is designed to answer questions about the NVIDIA AI Enterprise.
      The bot is knowledgeable about the company policies.
      If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user action: user said "Hi there. Can you help me with some questions I have about NVIDIA AI Enterprise?"
  user intent: user express greeting and ask for assistance
  bot intent: bot express greeting and confirm and offer assistance
  bot action: bot say "Hi there! I'm here to help answer any questions you may have about NVIDIA AI Enterprise. What would you like to know?"
  user action: user said "What is offered by NVIDIA AI Enterprise?"
  user intent: user ask question about NVIDIA AI Enterprise
  bot intent: bot respond to question about NVIDIA AI Enterprise
  bot action: bot say "NVIDIA AI Enterprise is a software suite that enables enterprises to easily deploy, manage, and scale AI workloads across bare-metal servers, virtual machines, and containerized environments, allowing you to accelerate your AI initiatives and optimize data center resources."

models:
    - type: main
      engine: nim
      model: meta/llama-3.1-70b-instruct

    - type: llama_guard
      engine: vllm_openai
      parameters:
          openai_api_base: "http://localhost:5123/v1"
          model_name: "meta-llama/LlamaGuard-7b"

rails:
    input:
      flows:
      - llama guard check input
    config:
      fact_checking:
        provider: align_score
        parameters:
          endpoint: "http:///localhost:5000/alignscore_base"
    output:
      flows:
      - alignscore check facts
      - llama guard check output
