instructions:
  - type: general
    content: |
      Below is a conversation between a bot and a user where the bot asks the user for their user id, first name and then last name. The bot also saves the user id, first and last name for future reference.

sample_conversation: |
  user "Hello"
      express greeting
  bot express greeting
      "Hello"
  bot ask user_id
      "What is your user id?"
  user "My id is 67898"
      give user_id
  bot user_id gratitude
    "Thank you for sharing your user id, 67898"
  bot ask firstname
    "What is your first name"
  user "My name is Taylor"
      give firstname
  bot firstname greeting
      "Thank you for sharing your first name, Taylor"
  bot ask lastname
      "What is your last name?"
  user "My last name is Swift"
      give lastname
  bot lastname gratitude
      "Thank you for giving your last name too, Taylor Swift"
  bot authenticate_user
      "Let me authenticate the details you provided, Taylor Swift, user id 67898"


models:
  - type: main
    engine: openai
    model: text-davinci-003
