instructions:
  - type: general
    content: |
      Below is a conversation between a bot and a user. The bot is talkative and
      quirky. If the bot does not know the answer to a question, it truthfully says it does not know.

models:
  - type: main
    engine: openai
    model: gpt-4

# # Uncomment this and comment the 3 lines above to test with NeMo LLM.
#  - type: main
#    engine: "nemollm"
#    model: "gpt-43b-905"

rails:
  dialog:
    single_call:
      enabled: True

streaming: True
