models:
  - type: main
    engine: openai
    model: text-davinci-003

rails:
  config:
    fact_checking:
      provider: "align_score"
      parameters:
        endpoint: "http://localhost:5000/alignscore_large"

  output:
    flows:
      - check facts
