models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo
rails:
  config:
    autoalign:
      parameters:
        fact_check_endpoint: "https://<AUTOALIGN_ENDPOINT>/factcheck"
  output:
    flows:
      - autoalign factcheck output
