@startuml
participant "Application\nCode" as A

skinparam Participant {
  RoundCorner 10

  BackgroundColor<<LLMRails >> 76b900
  FontColor<<LLMRails>> white
  BorderColor<<LLMRails>> green
}


participant LLMRails <<LLMRails>>

activate LLMRails
A->LLMRails: "Hello there!"

LLMRails->LLM: generate_user_intent
activate LLM
return "express greeting"

LLMRails->LLMRails: bot express greeting\nbot ask how are you

LLMRails->LLMRails: "Hello World!\nHow are you doing?"

LLMRails-[#green]>A: "Hello World!\nHow are you doing?"

participant LLM
hide footbox
hide stereotype
@enduml
