@startuml
participant "Application\nCode" as A

skinparam Participant {
  RoundCorner 10

  BackgroundColor<<LLMRails>> 76b900
  FontColor<<LLMRails>> white
  BorderColor<<LLMRails>> green
}


participant "Programmable\nGuardrails" as LLMRails <<LLMRails>>
participant "Input\nRails" as IR <<LLMRails>>
participant Actions
participant "LLM"


Activate A
A->LLMRails: <<USER MESSAGE>>
activate LLMRails

LLMRails->IR: <<USER MESSAGE>>
activate IR

IR->Actions: execute check_jailbreak
activate Actions

Actions->LLM: TaskPrompt [jailbreak_check]
activate LLM
return "Yes"

return False

return Stop

LLMRails->LLMRails: bot inform cannot answer

LLMRails->LLMRails: "I am not able to ..."

return #green "I am not able to ..."


hide footbox
hide stereotype
scale 2
@enduml
