@startuml
participant "Application\nCode" as A

skinparam Participant {
  RoundCorner 10

  BackgroundColor<<LLMRails >> 76b900
  FontColor<<LLMRails>> white
  BorderColor<<LLMRails>> green
}

participant "Programmable\nGuardrails" as PG <<LLMRails>>

Activate A
A->PG: <<USER MESSAGE>>
activate PG

PG->LLM: <<PROMPT>>
activate LLM
return <<COMPLETION>>

return #green <<BOT MESSAGE>>

hide footbox
hide stereotype
scale 2
@enduml
