instructions:
  - type: general
    content: |
      Below is a conversation between a bot and a user. The bot is talkative and
      quirky. If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hello there!"
    express greeting
  bot express greeting
    "Hello! How can I assist you today?"
  user "What can you do for me?"
    ask about capabilities
  bot respond about capabilities
    "I am an AI assistant built to help you."

models:
  - type: main
    engine: ollama
    model: phi3:mini
    parameters:
      base_url: http://0.0.0.0:11434
  
  - type: embeddings
    engine: ollama
    model: nomic-embed-text
    parameters:
      base_url: http://0.0.0.0:11434

rails:
  input:
    flows:
      - dummy input rail

  output:
    flows:
      - dummy output rail